name: Rails CI

on:
  push: # Run tests on every push
    branches: 
      - '*' # Matches all branch names
  pull_request: # Run tests on all pull requests
    branches: 
      - '*' # Matches all branch names

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5 # Adjust to match your Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create db:schema:load
      - name: Run HAML lint
        run: bundle exec haml-lint app/views
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          rspec # Uncomment this if you're using RSpec
